### ISSUE TITLE
Change license to CC-BY 4.0

### ISSUE THREAD

**Issue by gchure** [RPGroup-PBoC/RegSeq#18]
Is there a reason that  the current licensing is set to be CC-BY-ND? To me that seems a bit too restrictive of a license. 

The text of the CC-BY-ND license *does not* permit someone to take this code and modify it themselves:

> NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material. 

Given the nature of our scientific enterprise, It seems like you would want to license this under CC-BY 4.0 which permits derivation and release: 

>  Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

I'd like to hear any thoughts against making the license more permissive.

**Comment by gchure** [comment]
Saw this was closed without a change. If there’s a reason this is released with restrictive permissions I would really like to know why. It will have **significant** impacts towards how people use this software in the future.

**Comment by gchure** [comment]
I see now that the text of the license is now CC-BY 4, but the badge is still for ND. Since copyright laws (US) default to the most restrictive in cases of ambiguity, the badge takes precedence here and should be updated.

**Comment by tomroesch** [comment]
Fixed the badge to the right license.
