### ISSUE TITLE
add gene selector to this GitHub from paper

### ISSUE THREAD

**Issue by nikomccarty** [RPGroup-PBoC/RegSeq#5]

**Comment by gchure** [comment]
Can you give a description for what you mean here?

**Comment by nikomccarty** [comment]
Bill could potentially add the gene selector page from the other GitHub (https://github.com/RPGroup-PBoC/RNAseq_SortSeq) to this GitHub. Make this change only if you wish to make this the new, official GitHub repo for the Reg-Seq paper. Otherwise, it will serve as a "standalone" repo for educating others on how to perform the Reg-Seq protocol.
