### ISSUE TITLE
add MCMC practice file for auto_peak_call.ipynb

### ISSUE THREAD

**Issue by nikomccarty** [RPGroup-PBoC/RegSeq#6]
Bill - please add a sample dataset for the auto_peak_call.ipynb file.

**Comment by nikomccarty** [comment]
It says: "You can download this data from the github repo or as a .tar.gz file from the website under the datasets section." But we don't have a datasets section yet. Perhaps we could clean up that folder.

**Comment by tomroesch** [comment]
@irelandb Needs to be fixed.
